In [19]:
import numpy as np


In [44]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def LogRegGradient(X: np.array, y: np.array, w: np.array, C: float=1.0) -> np.array:
    m = X.shape[0]
    
    y_pred = sigmoid(X.dot(w))
    
    diff = y_pred - y
    g =  (X.T.dot(diff) + C * w) / m
    
    return g

In [ ]:
def LogRegGradient(X: np.array, y: np.array, w: np.array, C: float = 1.0) -> np.array:
    
    

In [45]:
for it in range(100):
    X_test2 = np.random.rand(50, 3)
    y_test2 = np.random.randint(2, size=50)
    w_test2 = np.random.rand(3)
    C_test2 = 1.0
    gradient_test2 = LogRegGradient(X_test2, y_test2, w_test2, C_test2)
    # print(gradient_test2)
    # print(LogRegGradient(X_test2, y_test2, w_test2))
    assert np.array_equal(gradient_test2, LogRegGradient(X_test2, y_test2, w_test2))

In [17]:
X_test3 = np.random.rand(50, 3)
y_test3 = np.random.randint(2, size=50)
w_test3 = np.random.rand(3)
gradient_with_regularization_test3 = log_reg_gradient(X_test3, y_test3, w_test3, C=1.0)
gradient_without_regularization_test3 = log_reg_gradient(X_test3, y_test3, w_test3, C=0.0)

In [18]:
print(gradient_with_regularization_test3)
print(gradient_without_regularization_test3)

[0.12856186 0.11402583 0.16191932]
[0.12856186 0.09612126 0.14436525]


In [11]:
print(gradient_test2)
print(log_reg_gradient(X_test2, y_test2, w_test2))

[0.06949869 0.04174784 0.12539331]
[0.06949869 0.04174784 0.12539331]


In [12]:
assert not np.array_equal(gradient_test2, log_reg_gradient(X_test2, y_test2, w_test2))

AssertionError: 

In [16]:
def run_local_tests():
    # Test 1: Check gradient shape
    X_test1 = np.random.rand(50, 3)
    y_test1 = np.random.randint(2, size=50)
    w_test1 = np.random.rand(3)
    gradient_test1 = log_reg_gradient(X_test1, y_test1, w_test1)
    assert gradient_test1.shape == w_test1.shape, "Test 1 failed: Gradient shape does not match weight shape"

    # Test 3: Check regularization with C=0.0
    X_test3 = np.random.rand(50, 3)
    y_test3 = np.random.randint(2, size=50)
    w_test3 = np.random.rand(3)
    gradient_with_regularization_test3 = log_reg_gradient(X_test3, y_test3, w_test3, C=1.0)
    gradient_without_regularization_test3 = log_reg_gradient(X_test3, y_test3, w_test3, C=0.0)

    # Check if regularization term is not present when C=0
    assert np.array_equal(gradient_with_regularization_test3, gradient_without_regularization_test3), "Test 3 failed: Regularization term is present with C=0"

    print("All tests passed.")

# Example usage:
run_local_tests()

AssertionError: Test 3 failed: Regularization term is present with C=0