In [2]:
import numpy as np

vector = np.array([1, 2, 7])
vector

array([1, 2, 7])

In [3]:
print(vector.dtype)
float_vector = np.array([-0.1, 1.123])
print(float_vector.dtype)

int64
float64


In [4]:
x = np.linspace(0, 1, num=5)
y = np.arange(1, 6)
z = np.zeros(5)
print(x)
print(y)
print("Zero vector:", z)

[0.   0.25 0.5  0.75 1.  ]
[1 2 3 4 5]
Zero vector: [0. 0. 0. 0. 0.]


In [5]:
print("Sum:", x+y)
print("Diff:", y-x)

Sum: [1.   2.25 3.5  4.75 6.  ]
Diff: [1.   1.75 2.5  3.25 4.  ]


In [6]:
print(-y)

[-1 -2 -3 -4 -5]


In [8]:
print("1-norm =", np.linalg.norm(y, ord=1))
print("2-norm =", np.linalg.norm(y, ord=2))
print("10-norm =", np.linalg.norm(y, ord=10))
print("infinite norm =", np.linalg.norm(y, ord=np.inf))

1-norm = 15.0
2-norm = 7.416198487095663
10-norm = 5.054055784535375
infinite norm = 5.0


In [9]:
def coppersmith_winograd(A, B):
    n = len(A)
    
    if n == 1:
        return [[A[0][0] * B[0][0]]]

    # Split matrices into four quarters
    a11 = [row[:n//2] for row in A[:n//2]]
    a12 = [row[n//2:] for row in A[:n//2]]
    a21 = [row[:n//2] for row in A[n//2:]]
    a22 = [row[n//2:] for row in A[n//2:]]
    
    b11 = [row[:n//2] for row in B[:n//2]]
    b12 = [row[n//2:] for row in B[:n//2]]
    b21 = [row[:n//2] for row in B[n//2:]]
    b22 = [row[n//2:] for row in B[n//2:]]
    
    # Recursive calls for matrix multiplications
    p1 = coppersmith_winograd(a11, b11)
    p2 = coppersmith_winograd(a12, b21)
    p3 = coppersmith_winograd(a11, b12)
    p4 = coppersmith_winograd(a12, b22)
    p5 = coppersmith_winograd(a21, b11)
    p6 = coppersmith_winograd(a22, b21)
    p7 = coppersmith_winograd(a21, b12)
    p8 = coppersmith_winograd(a22, b22)
    
    # Calculate the four quadrants of the result matrix
    c11 = [[p1[i][j] + p2[i][j] + p3[i][j] + p4[i][j] for j in range(n//2)] for i in range(n//2)]
    c12 = [[p5[i][j] + p6[i][j] for j in range(n//2)] for i in range(n//2)]
    c21 = [[p7[i][j] + p8[i][j] for j in range(n//2)] for i in range(n//2)]
    c22 = [[p1[i][j] + p2[i][j] for j in range(n//2)] for i in range(n//2)]

    # Combine the four quadrants to get the result matrix
    C = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(n//2):
        for j in range(n//2):
            C[i][j] = c11[i][j]
            C[i][j + n//2] = c12[i][j]
            C[i + n//2][j] = c21[i][j]
            C[i + n//2][j + n//2] = c22[i][j]
    
    return C

# Example usage
A = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
     [13, 14, 15, 16]]

B = [[16, 15, 14, 13],
     [12, 11, 10, 9],
     [8, 7, 6, 5],
     [4, 3, 2, 1]]

result = coppersmith_winograd(A, B)
for row in result:
    print(row)


[260, 428, 758, 560]
[376, 140, 502, 400]
[590, 444, 150, 240]
[386, 316, 214, 80]
